# Numpy Basic Operations

In [2]:
import numpy as np
my_list=[1,2,3,4]

In [3]:
np.array(my_list)

array([1, 2, 3, 4])

In [13]:
d2=[[1,2,3],[4,5,6],[7,8,9]]
d2

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [12]:
np.array(d2)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
#類似range的function，arange都只能產生一維的資料
s=np.arange(0,10,2)
s

array([0, 2, 4, 6, 8])

In [32]:
# build 一個 都是 0 向量或是矩陣，第一個參數代表shape
np.zeros((2,3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [34]:
np.ones((2,3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [49]:
#可以以小數點作為interval 
#每次間隔為 (end-start)/第三個參數 => 在這個區間產生 第三個參數的量
np.linspace(0,5,100) 

array([ 0.        ,  0.05050505,  0.1010101 ,  0.15151515,  0.2020202 ,
        0.25252525,  0.3030303 ,  0.35353535,  0.4040404 ,  0.45454545,
        0.50505051,  0.55555556,  0.60606061,  0.65656566,  0.70707071,
        0.75757576,  0.80808081,  0.85858586,  0.90909091,  0.95959596,
        1.01010101,  1.06060606,  1.11111111,  1.16161616,  1.21212121,
        1.26262626,  1.31313131,  1.36363636,  1.41414141,  1.46464646,
        1.51515152,  1.56565657,  1.61616162,  1.66666667,  1.71717172,
        1.76767677,  1.81818182,  1.86868687,  1.91919192,  1.96969697,
        2.02020202,  2.07070707,  2.12121212,  2.17171717,  2.22222222,
        2.27272727,  2.32323232,  2.37373737,  2.42424242,  2.47474747,
        2.52525253,  2.57575758,  2.62626263,  2.67676768,  2.72727273,
        2.77777778,  2.82828283,  2.87878788,  2.92929293,  2.97979798,
        3.03030303,  3.08080808,  3.13131313,  3.18181818,  3.23232323,
        3.28282828,  3.33333333,  3.38383838,  3.43434343,  3.48

In [54]:
#對角線為1的對角線矩陣 (一定是個方陣)
np.eye(5)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [61]:
#隨機產生後面維度的向量或是矩陣，值為 0 ~ 1 之間
np.random.rand(20,3)

array([[  1.50576510e-01,   4.64167738e-01,   1.97365344e-01],
       [  1.65895808e-01,   3.76234682e-01,   2.23115115e-01],
       [  6.94863863e-01,   3.31622560e-01,   7.03224405e-01],
       [  7.06392574e-01,   3.30036678e-01,   4.57663139e-02],
       [  1.38047436e-01,   2.04134590e-01,   8.32081577e-01],
       [  8.54683123e-04,   4.41176558e-01,   5.52841246e-01],
       [  2.32911315e-01,   1.30214035e-01,   3.26539273e-01],
       [  4.88775159e-02,   8.22965181e-01,   1.21409303e-01],
       [  6.20688971e-01,   1.86997543e-01,   6.57303328e-02],
       [  2.22685059e-01,   8.23888031e-01,   8.27641535e-01],
       [  6.45740908e-01,   6.86461564e-01,   3.10921779e-01],
       [  4.58602001e-01,   8.00016474e-02,   2.02022592e-01],
       [  8.41554455e-01,   8.73698254e-01,   4.88323688e-01],
       [  1.95061685e-01,   1.66412004e-02,   4.05030683e-01],
       [  6.38894390e-01,   2.98872508e-01,   2.65355517e-01],
       [  7.48721964e-02,   1.25158349e-01,   7.0157495

In [71]:
#跟range不包含尾數
np.random.randint(1,10,(3,5))

array([[7, 2, 4, 9, 2],
       [5, 6, 2, 3, 3],
       [5, 7, 6, 8, 5]])

In [74]:
#normal distribution
np.random.randn(20,4)

array([[-0.17087033,  0.51314118,  1.91391398, -0.87843644],
       [-0.01504549, -0.73062963, -0.52016377, -1.42636758],
       [-1.21745474, -0.76117243, -0.71289685,  1.30761617],
       [-0.40041197,  0.01294551, -1.61300812,  0.5463818 ],
       [-0.51632145, -0.85118532,  0.52734436,  1.7593277 ],
       [-0.15774432,  1.34415176,  1.22659557,  0.43538898],
       [-0.77546218,  0.735348  ,  0.99857169, -0.44461965],
       [ 1.69073551,  1.19134986,  0.08165462,  0.31596456],
       [-1.24658905,  1.04971971, -1.20641769,  0.74054547],
       [ 0.14545813, -0.72186928,  1.68214337, -0.5347701 ],
       [ 0.48455684, -0.5940322 ,  0.01452005, -1.51016703],
       [-0.84822096, -0.1175265 , -0.18426004,  1.54132759],
       [-0.41101139,  1.08293251, -1.89163853, -0.30978301],
       [ 0.26924342,  0.55487511,  1.10852512,  0.03954052],
       [ 0.56332349,  0.39840884,  1.76880101,  0.82138551],
       [-0.61085946,  0.70155184, -1.39951274, -1.19592997],
       [-0.86485829, -1.

In [82]:
arr=np.arange(30)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [86]:
#重新構築維度
arr.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [118]:
#沒有只掉第三個參數，應該就是只有一個」
rnarr=np.random.randint(1,50,30)
rnarr

array([12, 40, 25, 18, 12, 27, 49, 24, 17,  1,  7, 24, 35, 46, 10, 47, 45,
       34, 42,  3, 38, 17, 16, 47, 42, 16,  7, 39, 27,  4])

In [119]:
rnarr=rnarr.reshape(5,6)

In [120]:
rnarr.max()

49

In [121]:
rnarr.min()

1

In [122]:
#回傳最大的值的index是哪一個，他會先把維度flattern成一維的資料
rnarr.argmax()

6

In [123]:
rnarr.argmin()

9

In [124]:
rnarr.shape

(5, 6)

In [110]:
rnarr.dtype

dtype('int64')

In [126]:
rnarr

array([[12, 40, 25, 18, 12, 27],
       [49, 24, 17,  1,  7, 24],
       [35, 46, 10, 47, 45, 34],
       [42,  3, 38, 17, 16, 47],
       [42, 16,  7, 39, 27,  4]])

In [133]:
rnarr[2,3]

47

# Numpy Array indexing

In [136]:
arr = np.arange(0,11) 
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [149]:
# broadcast assign value
arr[3:]=2

In [151]:
arr=np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [163]:
arr2d=np.array([[5,10,15],[20,25,30],[35,40,45]])
arr2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [166]:
arr2d[2,1:]

array([40, 45])

In [185]:
arr2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [188]:
arr2d[:2,[-1,-2]]

array([[15, 10],
       [30, 25]])

In [190]:
arr=np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [193]:
#加一個條件值，各值會回傳 True or False 可以當作mask，就很像是DataFrame的Series
arr[arr > 5]

array([ 6,  7,  8,  9, 10])

In [195]:
arr[arr%2>0]

array([1, 3, 5, 7, 9])

In [201]:
#用二維的話，結果會以一維呈現
arr2d[arr2d>20]

array([25, 30, 35, 40, 45])

In [202]:
arr[arr<3]

array([1, 2])

In [203]:
arr_2d=np.arange(50).reshape(5,10)

In [204]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [224]:
arr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])

In [235]:
arr_2d[arr_2d>20]

array([21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37,
       38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

# Numpy Opearions (array 之間還可以做加減程組，類似每個值都 map)
- Array with Array
- Array with Scalar
- Universal Array Function

In [236]:
import numpy as np

In [237]:
arr=np.arange(0,11)

In [238]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [241]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [242]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [243]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [264]:
arr * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [245]:
arr - 100

array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91,  -90])

In [251]:
#when it occurs the worng mathemetical problem, numpy will not throw warning, like below 
arr/arr

/Users/jiajiaping/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in true_divide
  


array([ nan,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.])

In [252]:
1/arr

/Users/jiajiaping/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([        inf,  1.        ,  0.5       ,  0.33333333,  0.25      ,
        0.2       ,  0.16666667,  0.14285714,  0.125     ,  0.11111111,
        0.1       ])

In [253]:
1 / arr

/Users/jiajiaping/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([        inf,  1.        ,  0.5       ,  0.33333333,  0.25      ,
        0.2       ,  0.16666667,  0.14285714,  0.125     ,  0.11111111,
        0.1       ])

In [261]:
#針對每個值開根號
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766])

In [262]:
np.exp(arr) #底數是 e 次方為值

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03,   2.20264658e+04])

In [265]:
arr.max()

10

In [267]:
#全部指派為sin值
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [268]:
np.log(arr)

/Users/jiajiaping/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([       -inf,  0.        ,  0.69314718,  1.09861229,  1.38629436,
        1.60943791,  1.79175947,  1.94591015,  2.07944154,  2.19722458,
        2.30258509])